spring:
  application:
    name: CouponVoucherService

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.egwwpaoacecgkdaycggp&password=AnmolMehla@6228&sslmode=require
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # testing only
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource.hikari:
    maximum-pool-size: 5